export const bookmarks = [
  {
    id: 1,
    title: "UI Libraries",
    url: "ui-libraries",
    contents: [
      "https://nextui.org/",
      "https://ui.shadcn.com/",
      "https://mui.com/",
      "https://www.radix-ui.com/",
      "https://v2.chakra-ui.com/",
      "https://primereact.org/",
      "https://preline.co/",
      "https://ant.design/",
    ],
  },
  {
    id: 2,
    title: "Icons",
    url: "icons",
    contents: [
      "https://lucide.dev/",
      "https://fontawesome.com/",
      "https://lordicon.com/",
      "https://ionic.io/ionicons",
      "https://heroicons.com/",
      "https://hugeicons.com/",
      "https://iconoir.com/",
      "https://feathericons.com/",
      "https://mui.com/material-ui/material-icons/",
      "https://boxicons.com/",
    ],
  },
  /* {
    id: 3,
    title: 'VS Code',
    url: 'vs-code',
    contents: [
      "https://marketplace.visualstudio.com/items?itemName=dsznajder.es7-react-js-snippets",
      "https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint",
      "https://marketplace.visualstudio.com/items?itemName=ChakrounAnas.turbo-console-log",
      "https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens",
      "https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss",
      "https://marketplace.visualstudio.com/items?itemName=sibiraj-s.vscode-scss-formatter",
      "https://marketplace.visualstudio.com/items?itemName=rvest.vs-code-prettier-eslint",
      "https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode",
      "https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme-icons",
      "https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme",
      "https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme",
      "https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer",
      "https://marketplace.visualstudio.com/items?itemName=xabikos.JavaScriptSnippets",
      "https://marketplace.visualstudio.com/items?itemName=pranaygp.vscode-css-peek",
      "https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag",
      "https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-complete-tag",
      "https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag",
      "https://marketplace.visualstudio.com/items?itemName=Prabhakar.copy",
    ],
  }, */
  {
    id: 4,
    title: "API",
    url: "api",
    contents: [
      "https://axios-http.com/",
      "https://dub.co/",
      "https://dummyjson.com/",
    ],
  },
];
